### ISSUE TITLE
model optimized with ms-ssim

### ISSUE THREAD

**Issue by nshidqi** [Googolxx/STF#20]
Hi, 
Thank you for your great work!

In the paper, you mentioned that your models were optimized by MSE and MS_SSIM.
However, in the codes, i didn't see it's optimized with ms-ssim.
Could you please help to advise on this?

Thank you!

**Comment by Googolxx** [comment]
Hi,
Both MSE and MS-SSIM are used to optimize the model in original paper.
But in this repo, the codes were reorganized, and I trained the models from scratch optimized by MSE instead of MS-SSIM.
So the MS-SSIM optimized pertained models haven't been released.
To get the MS-SSIM optimized models, you got to train from scratch using MS-SSIM. Sorry for that.

**Comment by nshidqi** [comment]
Okay, thank you!
