### ISSUE TITLE
Plug and Play

### ISSUE THREAD

**Issue by xiaoyudanaa** [Googolxx/STF#4]
Hello, I put the Win_noShift_Attention in your code into my project, but the effect decreased, I guess I deployed it incorrectly. Can you tell me how to configure this module. My direction is monocular depth estimation

**Comment by Googolxx** [comment]
Sorry for late. The Window-based Attention is a local attention mechanism, it works in image compression because of the local spatial redundancy within images, which means it may not be suitable for other tasks.
I think you can try the [non-local attention mechanism](https://github.com/AlexHex7/Non-local_pytorch) instead for contrast.
I don't get "how to configure this module?", means how to set the hyperparameters of the module or where to put it, or something else?
